#!/bin/bash
# accept filename of spam to be reported
# don't report spam older than $2 hours
if [ "x$1" = "x" ]  
then
	echo "Which message to report?"
	exit 1
fi
MIN=`echo "${2:-9} * 60" | bc`
SUBMIT=`find /var/tmp/sent -mindepth 1 -maxdepth 1 -mmin -$MIN | grep $1`
if [ "x$SUBMIT" != "x" ]
then
	DETA=`date -R`; 
	cat /var/tmp/sent/$1 | mail -s "Spam from $DETA" $YOUR_IDENTIFIER@spam.spamcop.net
fi
