#!/bin/bash
cd /var/tmp/sent
NUMBER=`ls -1 out.* | wc -l`
echo "$NUMBER messages to process."
NO=`egrep -li 'elided' out.*`
for I in $NO
do
	cat $I | egrep -q 'X-Spam-Level:.\*'
	if [ $? = 0 ]
	then
		echo ""
		echo "Submitting $I as spam and moving to old folder."
		sendtospamcop $I
	fi
	mv -i $I old
done
for I in out.*
do
	echo ""
	echo $I
	grep -i ^From: $I
	grep -i ^To: $I
	grep -i ^Subject: $I
        grep -i ^Date: $I
	echo ""
	echo -n "Mark $I as spam? [y/n/Q]: "
	read SPAM
	case $SPAM in
	[yY]) 
		SPAMS=("${SPAMS[@]}" $I)
	;;
	[nN])
		HAMS=("${SPAMS[@]}" $I)
	;;
	*)
		for FUCK in "${SPAMS[@]}"
		do
			echo "Marking, submitting and archiving $FUCK as spam."
			sa-learn --spam $FUCK
			sendtospamcop $FUCK
			mv $FUCK old
		done
		for YAY in "${HAMS[@]}"
		do
			echo "Marking and archiving $YAY as ham."
			sa-learn --ham $YAY
			mv $YAY old
		done
	;;
	esac
done
cd -
